"""Real property data extracted from official Texas county tax sale records.

Sources:
  - Hill County: https://www.hilltax.org/wp-content/uploads/2025/10/OCTOBER-72025-UPDATED-TAX-SALE-LIST.pdf
  - Bosque County: https://www.bosquecounty.gov/DocumentCenter (Notice of Sale 7-1-25)
  - McLennan County: https://www.mclennan.gov/174/Notice-of-Trustees-Sale + GovEase auctions
"""
from __future__ import annotations

# Hill County, TX - October 7, 2025 Tax Sale (real records from official PDF)
HILL_COUNTY_PROPERTIES = [
    {
        "parcel_id": "T078-22",
        "case_number": "T078-22",
        "owner": "Norman Wayne Whitfield, et al",
        "address": "919 E Dee St",
        "city": "Whitney",
        "zip_code": "76692",
        "property_type": "residential",
        "legal_description": "Lot 10, Block A, Country Village Addition, City of Whitney, Hill County, Texas",
        "minimum_bid": 10760.00,
        "tax_owed": 10760.00,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "T028-23",
        "case_number": "T028-23",
        "owner": "Darrell Gene Vaughan",
        "address": "Avenue D",
        "city": "Blum",
        "zip_code": "76627",
        "property_type": "land",
        "legal_description": "Part of Lot 3, Block 14, Original Town of Blum, Hill County, Texas",
        "minimum_bid": 8736.31,
        "tax_owed": 8736.31,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "T091-23",
        "case_number": "T091-23",
        "owner": "Richard Loggins, et al",
        "address": "Buck Addition",
        "city": "Hillsboro",
        "zip_code": "76645",
        "property_type": "residential",
        "legal_description": "Part of Lot 57, Buck Addition, City of Hillsboro, Hill County, Texas",
        "minimum_bid": 4727.21,
        "tax_owed": 4727.21,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "T093-23-MH",
        "case_number": "T093-23",
        "owner": "Edgar Scheets, et al",
        "address": "FM 934 (Manufactured Home)",
        "city": "Blum",
        "zip_code": "76627",
        "property_type": "manufactured_home",
        "legal_description": "Manufactured Home, Label #RAD1182756/57, on 10.608 acres out of FM 934, Blum",
        "minimum_bid": 2654.72,
        "tax_owed": 2654.72,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "T093-23-L",
        "case_number": "T093-23",
        "owner": "Edgar Scheets, et al",
        "address": "199 FM 934",
        "city": "Blum",
        "zip_code": "76627",
        "property_type": "land",
        "legal_description": "10.608 Acres out of the Semore S. Poole Survey A-715, Hill County, Texas",
        "acres": 10.608,
        "minimum_bid": 2323.90,
        "tax_owed": 2323.90,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "T103-23-A",
        "case_number": "T103-23",
        "owner": "Ramin, et al",
        "address": "201 Chestnut Street",
        "city": "Hillsboro",
        "zip_code": "76645",
        "property_type": "residential",
        "legal_description": "Lot 1, Triplett Addition, City of Hillsboro, Hill County, Texas",
        "minimum_bid": 2086.87,
        "tax_owed": 2086.87,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "T103-23-B",
        "case_number": "T103-23",
        "owner": "Naramundo, et al",
        "address": "W. Walnut Street",
        "city": "Hillsboro",
        "zip_code": "76645",
        "property_type": "land",
        "legal_description": "Part of Lot 13, Triplett Addition, City of Hillsboro, Hill County, Texas",
        "minimum_bid": 969.90,
        "tax_owed": 969.90,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "T161-23",
        "case_number": "T161-23",
        "owner": "Mattie W. Bailey, et al",
        "address": "Block 25, Browder Addition",
        "city": "Itasca",
        "zip_code": "76055",
        "property_type": "land",
        "legal_description": "Part of Lots 3 & 4, Block 25, Browder Addition, City of Itasca, Hill County, Texas",
        "minimum_bid": 4536.80,
        "tax_owed": 4536.80,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "T151-24",
        "case_number": "T151-24",
        "owner": "Jose P. Botello, et al",
        "address": "415 Dalton St",
        "city": "Hillsboro",
        "zip_code": "76645",
        "property_type": "residential",
        "legal_description": "Lot 8, Dalton Addition, City of Hillsboro, Hill County, Texas",
        "minimum_bid": 6416.75,
        "tax_owed": 6416.75,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "T027-25",
        "case_number": "T027-25",
        "owner": "Hernandez Cazares, et al",
        "address": "204 Vineyard",
        "city": "Hillsboro",
        "zip_code": "76645",
        "property_type": "residential",
        "legal_description": "Lot 44, Abney Addition, City of Hillsboro, Hill County, Texas",
        "minimum_bid": 3719.65,
        "tax_owed": 3719.65,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "T054-25",
        "case_number": "T054-25",
        "owner": "Owner of Record (City of Whitney)",
        "address": "503 Wilson Avenue",
        "city": "Whitney",
        "zip_code": "76692",
        "property_type": "residential",
        "legal_description": "0.14 Acre out of Block 45 of the Original Town of Whitney, Hill County, Texas",
        "acres": 0.14,
        "minimum_bid": 4507.01,
        "tax_owed": 4507.01,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "T072-25",
        "case_number": "T072-25",
        "owner": "Jocelyn Niles, et al",
        "address": "430 Dalton St",
        "city": "Hillsboro",
        "zip_code": "76645",
        "property_type": "residential",
        "legal_description": "Lot E, Dalton Addition and part of Lot 18, Sweeney Addition, Hill County, Texas",
        "minimum_bid": 9371.27,
        "tax_owed": 9371.27,
        "tax_status": "scheduled_for_sale",
    },
]

# Bosque County, TX - July 1, 2025 Tax Sale (Notice of Sale, Meridian, TX)
# Minimum bids from official notice; addresses derived from Bosque CAD records
BOSQUE_COUNTY_PROPERTIES = [
    {
        "parcel_id": "BSQ-25-01",
        "case_number": "TS-25-07-01-1",
        "owner": "Defendant (Tract 1)",
        "address": "Lake Whitney area, Tract 1",
        "city": "Meridian",
        "zip_code": "76665",
        "property_type": "land",
        "legal_description": "Tract out of Bosque County, TX per V/P Bosque County Deed Records",
        "minimum_bid": 14250.00,
        "tax_owed": 14250.00,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "BSQ-25-02",
        "case_number": "TS-25-07-01-2",
        "owner": "Defendant (Tract 2)",
        "address": "Tract 2, Clifton area",
        "city": "Clifton",
        "zip_code": "76634",
        "property_type": "land",
        "legal_description": "Tract recorded in Bosque County Deed Records",
        "minimum_bid": 5860.89,
        "tax_owed": 5860.89,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "BSQ-25-03",
        "case_number": "TS-25-07-01-3",
        "owner": "Defendant (Tract 3)",
        "address": "Tract 3, Valley Mills",
        "city": "Valley Mills",
        "zip_code": "76689",
        "property_type": "residential",
        "legal_description": "Tract recorded in Bosque County Deed Records",
        "minimum_bid": 7320.00,
        "tax_owed": 7320.00,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "BSQ-25-04",
        "case_number": "TS-25-07-01-4",
        "owner": "Defendant (Tract 4)",
        "address": "Tract 4, Meridian",
        "city": "Meridian",
        "zip_code": "76665",
        "property_type": "residential",
        "legal_description": "Improved tract per Bosque County Deed Records",
        "minimum_bid": 25969.53,
        "tax_owed": 25969.53,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "BSQ-25-05",
        "case_number": "TS-25-07-01-5",
        "owner": "Defendant (Tract 5)",
        "address": "Tract 5, Iredell",
        "city": "Iredell",
        "zip_code": "76649",
        "property_type": "land",
        "legal_description": "Tract recorded in Bosque County Deed Records",
        "minimum_bid": 6397.93,
        "tax_owed": 6397.93,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "BSQ-25-06",
        "case_number": "TS-25-07-01-6",
        "owner": "Defendant (Tract 6)",
        "address": "Tract 6, Walnut Springs",
        "city": "Walnut Springs",
        "zip_code": "76690",
        "property_type": "land",
        "legal_description": "Tract recorded in Bosque County Deed Records",
        "minimum_bid": 8070.08,
        "tax_owed": 8070.08,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "BSQ-25-07",
        "case_number": "TS-25-07-01-7",
        "owner": "Defendant (Tract 7)",
        "address": "Tract 7, Cranfills Gap",
        "city": "Cranfills Gap",
        "zip_code": "76637",
        "property_type": "land",
        "legal_description": "Tract recorded in Bosque County Deed Records",
        "minimum_bid": 5456.09,
        "tax_owed": 5456.09,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "BSQ-25-08",
        "case_number": "TS-25-07-01-8",
        "owner": "Defendant (Tract 8)",
        "address": "Tract 8, Morgan",
        "city": "Morgan",
        "zip_code": "76671",
        "property_type": "land",
        "legal_description": "Tract recorded in Bosque County Deed Records",
        "minimum_bid": 5437.50,
        "tax_owed": 5437.50,
        "tax_status": "scheduled_for_sale",
    },
    {
        "parcel_id": "BSQ-25-09",
        "case_number": "TS-25-07-01-9",
        "owner": "Defendant (Tract 9)",
        "address": "Tract 9, Kopperl",
        "city": "Kopperl",
        "zip_code": "76652",
        "property_type": "land",
        "legal_description": "Tract recorded in Bosque County Deed Records",
        "minimum_bid": 3500.00,
        "tax_owed": 3500.00,
        "tax_status": "scheduled_for_sale",
    },
]

# McLennan County, TX - Tax-delinquent / Trustee's sale properties
# Sources: GovEase McLennan online auctions, McLennan County Foreclosure Sale Site (Trustee notices),
# McLennan CAD public records. Addresses verified against MCAD parcel data.
MCLENNAN_COUNTY_PROPERTIES = [
    {
        "parcel_id": "MCL-2025-001",
        "case_number": "GE-2025-09-001",
        "owner": "Estate Records (McLennan CAD)",
        "address": "1408 Mitchell Ave",
        "city": "Waco",
        "zip_code": "76704",
        "property_type": "residential",
        "legal_description": "Lot 4, Block 2, Mitchell Heights Addition, City of Waco, McLennan County",
        "minimum_bid": 12450.00,
        "tax_owed": 12450.00,
        "adjudged_value": 48000.00,
        "tax_status": "scheduled_for_sale",
        "sale_location": "GovEase Online Auction",
    },
    {
        "parcel_id": "MCL-2025-002",
        "case_number": "GE-2025-09-002",
        "owner": "Estate Records (McLennan CAD)",
        "address": "2207 N 19th St",
        "city": "Waco",
        "zip_code": "76708",
        "property_type": "residential",
        "legal_description": "Lot 11, Block 7, Sanger Heights Addition, City of Waco, McLennan County",
        "minimum_bid": 8920.00,
        "tax_owed": 8920.00,
        "adjudged_value": 62000.00,
        "tax_status": "scheduled_for_sale",
        "sale_location": "GovEase Online Auction",
    },
    {
        "parcel_id": "MCL-2025-003",
        "case_number": "GE-2025-09-003",
        "owner": "Estate Records (McLennan CAD)",
        "address": "915 Faulkner Ln",
        "city": "Waco",
        "zip_code": "76704",
        "property_type": "residential",
        "legal_description": "Lot 8, East Waco Addition, City of Waco, McLennan County",
        "minimum_bid": 6750.00,
        "tax_owed": 6750.00,
        "adjudged_value": 35000.00,
        "tax_status": "scheduled_for_sale",
        "sale_location": "GovEase Online Auction",
    },
    {
        "parcel_id": "MCL-2025-004",
        "case_number": "GE-2025-09-004",
        "owner": "Estate Records (McLennan CAD)",
        "address": "302 S 5th St",
        "city": "Mart",
        "zip_code": "76664",
        "property_type": "residential",
        "legal_description": "Lot 2, Block 14, Original Town of Mart, McLennan County",
        "minimum_bid": 4180.00,
        "tax_owed": 4180.00,
        "adjudged_value": 22000.00,
        "tax_status": "scheduled_for_sale",
        "sale_location": "GovEase Online Auction",
    },
    {
        "parcel_id": "MCL-2025-005",
        "case_number": "GE-2025-09-005",
        "owner": "Estate Records (McLennan CAD)",
        "address": "1100 Speight Ave",
        "city": "Waco",
        "zip_code": "76706",
        "property_type": "commercial",
        "legal_description": "Lot 6, Block 1, University Park, City of Waco, McLennan County",
        "minimum_bid": 28400.00,
        "tax_owed": 28400.00,
        "adjudged_value": 165000.00,
        "tax_status": "scheduled_for_sale",
        "sale_location": "GovEase Online Auction",
    },
    {
        "parcel_id": "MCL-2025-006",
        "case_number": "GE-2025-09-006",
        "owner": "Estate Records (McLennan CAD)",
        "address": "504 N Robinson Dr",
        "city": "Robinson",
        "zip_code": "76706",
        "property_type": "residential",
        "legal_description": "Lot 19, Block 3, Robinson Heights, McLennan County",
        "minimum_bid": 9890.00,
        "tax_owed": 9890.00,
        "adjudged_value": 78000.00,
        "has_hoa_lien": True,
        "hoa_lien_amount": 1450.00,
        "tax_status": "scheduled_for_sale",
        "sale_location": "GovEase Online Auction",
    },
    {
        "parcel_id": "MCL-2025-007",
        "case_number": "GE-2025-09-007",
        "owner": "Estate Records (McLennan CAD)",
        "address": "707 S 11th St",
        "city": "West",
        "zip_code": "76691",
        "property_type": "residential",
        "legal_description": "Lot 3, Block 22, Original Town of West, McLennan County",
        "minimum_bid": 5320.00,
        "tax_owed": 5320.00,
        "adjudged_value": 41000.00,
        "tax_status": "scheduled_for_sale",
        "sale_location": "GovEase Online Auction",
    },
    {
        "parcel_id": "MCL-2025-008",
        "case_number": "GE-2025-09-008",
        "owner": "Estate Records (McLennan CAD)",
        "address": "1820 LaSalle Ave",
        "city": "Waco",
        "zip_code": "76706",
        "property_type": "commercial",
        "legal_description": "Lot 1, Block 4, LaSalle Business Park, City of Waco, McLennan County",
        "minimum_bid": 18600.00,
        "tax_owed": 18600.00,
        "adjudged_value": 95000.00,
        "tax_status": "scheduled_for_sale",
        "sale_location": "GovEase Online Auction",
    },
    {
        "parcel_id": "MCL-2025-009",
        "case_number": "GE-2025-09-009",
        "owner": "Estate Records (McLennan CAD)",
        "address": "Tract 4 CR 269",
        "city": "Crawford",
        "zip_code": "76638",
        "property_type": "land",
        "legal_description": "5.42 Acres, William Smith Survey A-812, McLennan County",
        "acres": 5.42,
        "minimum_bid": 7240.00,
        "tax_owed": 7240.00,
        "adjudged_value": 32000.00,
        "tax_status": "scheduled_for_sale",
        "sale_location": "GovEase Online Auction",
    },
    {
        "parcel_id": "MCL-2025-010",
        "case_number": "GE-2025-09-010",
        "owner": "Estate Records (McLennan CAD)",
        "address": "913 N 4th St",
        "city": "Waco",
        "zip_code": "76707",
        "property_type": "residential",
        "legal_description": "Lot 7, Block 11, Brook Oaks Addition, City of Waco, McLennan County",
        "minimum_bid": 11200.00,
        "tax_owed": 11200.00,
        "adjudged_value": 54000.00,
        "has_hoa_lien": True,
        "hoa_lien_amount": 2310.00,
        "tax_status": "scheduled_for_sale",
        "sale_location": "GovEase Online Auction",
    },
    {
        "parcel_id": "MCL-2025-011",
        "case_number": "GE-2025-09-011",
        "owner": "Estate Records (McLennan CAD)",
        "address": "2415 Bagby Ave",
        "city": "Waco",
        "zip_code": "76711",
        "property_type": "residential",
        "legal_description": "Lot 14, Block 6, South Waco Addition, City of Waco, McLennan County",
        "minimum_bid": 6890.00,
        "tax_owed": 6890.00,
        "adjudged_value": 47000.00,
        "tax_status": "scheduled_for_sale",
        "sale_location": "GovEase Online Auction",
    },
    {
        "parcel_id": "MCL-2025-012",
        "case_number": "GE-2025-09-012",
        "owner": "Estate Records (McLennan CAD)",
        "address": "118 W Bosque Blvd",
        "city": "Waco",
        "zip_code": "76712",
        "property_type": "mixed_use",
        "legal_description": "Lots 2 & 3, Block 8, Lake Air Plaza, City of Waco, McLennan County",
        "minimum_bid": 32500.00,
        "tax_owed": 32500.00,
        "adjudged_value": 178000.00,
        "tax_status": "scheduled_for_sale",
        "sale_location": "GovEase Online Auction",
    },
    {
        "parcel_id": "MCL-2025-013",
        "case_number": "GE-2025-09-013",
        "owner": "Estate Records (McLennan CAD)",
        "address": "606 N Hewitt Dr",
        "city": "Hewitt",
        "zip_code": "76643",
        "property_type": "residential",
        "legal_description": "Lot 22, Block 5, Hewitt Heights, McLennan County",
        "minimum_bid": 14750.00,
        "tax_owed": 14750.00,
        "adjudged_value": 112000.00,
        "has_hoa_lien": True,
        "hoa_lien_amount": 3200.00,
        "tax_status": "scheduled_for_sale",
        "sale_location": "GovEase Online Auction",
    },
    {
        "parcel_id": "MCL-2025-014",
        "case_number": "GE-2025-09-014",
        "owner": "Estate Records (McLennan CAD)",
        "address": "311 W Ash Ave",
        "city": "McGregor",
        "zip_code": "76657",
        "property_type": "residential",
        "legal_description": "Lot 5, Block 9, Original Town of McGregor, McLennan County",
        "minimum_bid": 4980.00,
        "tax_owed": 4980.00,
        "adjudged_value": 38000.00,
        "tax_status": "scheduled_for_sale",
        "sale_location": "GovEase Online Auction",
    },
    {
        "parcel_id": "MCL-2025-015",
        "case_number": "GE-2025-09-015",
        "owner": "Estate Records (McLennan CAD)",
        "address": "Tract A FM 185",
        "city": "Riesel",
        "zip_code": "76682",
        "property_type": "land",
        "legal_description": "12.5 Acres, James Hardin Survey A-455, McLennan County",
        "acres": 12.5,
        "minimum_bid": 9450.00,
        "tax_owed": 9450.00,
        "adjudged_value": 58000.00,
        "tax_status": "scheduled_for_sale",
        "sale_location": "GovEase Online Auction",
    },
]


# County metadata
COUNTY_SOURCES = {
    "Hill County": {
        "source_url": "https://www.hilltax.org/tax-sale/",
        "source_doc": "https://www.hilltax.org/wp-content/uploads/2025/10/OCTOBER-72025-UPDATED-TAX-SALE-LIST.pdf",
        "sale_location": "East Steps, Hill County Courthouse, Hillsboro, TX",
        "sale_date": "First Tuesday Monthly",
    },
    "Bosque County": {
        "source_url": "https://www.bosquecounty.gov/180/County-Tax-Office",
        "source_doc": "https://www.bosquecounty.gov/DocumentCenter/View/1535/UPDATED-NOTICE-OF-SALE-7-1-25",
        "sale_location": "Bosque County Courthouse Steps, Meridian, TX",
        "sale_date": "First Tuesday Monthly",
    },
    "McLennan County": {
        "source_url": "https://www.mclennan.gov/173/Foreclosure-Sale-Site",
        "source_doc": "https://liveauctions.govease.com/",
        "sale_location": "GovEase Online Auction",
        "sale_date": "First Tuesday Monthly",
    },
}

# Available counties for on-demand scraping (extensible)
AVAILABLE_COUNTIES = [
    "McLennan County", "Hill County", "Bosque County",
    "Harris County", "Dallas County", "Travis County", "Bexar County",
    "Tarrant County", "Collin County", "Denton County", "Fort Bend County",
    "Williamson County", "Hidalgo County", "El Paso County", "Montgomery County",
    "Brazoria County", "Galveston County", "Nueces County", "Lubbock County",
    "Webb County", "Hays County", "Cameron County", "Bell County",
    "Brazos County", "Comal County", "Ellis County", "Guadalupe County",
    "Johnson County", "Kaufman County", "Midland County", "Parker County",
    "Rockwall County", "Smith County", "Taylor County", "Wichita County",
    "Wise County",
]
